/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YourListRouteImport } from './routes/your-list'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AddJobRouteImport } from './routes/add-job'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EditJobUuidRouteImport } from './routes/edit-job.$uuid'

const YourListRoute = YourListRouteImport.update({
  id: '/your-list',
  path: '/your-list',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AddJobRoute = AddJobRouteImport.update({
  id: '/add-job',
  path: '/add-job',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditJobUuidRoute = EditJobUuidRouteImport.update({
  id: '/edit-job/$uuid',
  path: '/edit-job/$uuid',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-job': typeof AddJobRoute
  '/login': typeof LoginRoute
  '/your-list': typeof YourListRoute
  '/edit-job/$uuid': typeof EditJobUuidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-job': typeof AddJobRoute
  '/login': typeof LoginRoute
  '/your-list': typeof YourListRoute
  '/edit-job/$uuid': typeof EditJobUuidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-job': typeof AddJobRoute
  '/login': typeof LoginRoute
  '/your-list': typeof YourListRoute
  '/edit-job/$uuid': typeof EditJobUuidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/add-job' | '/login' | '/your-list' | '/edit-job/$uuid'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/add-job' | '/login' | '/your-list' | '/edit-job/$uuid'
  id:
    | '__root__'
    | '/'
    | '/add-job'
    | '/login'
    | '/your-list'
    | '/edit-job/$uuid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddJobRoute: typeof AddJobRoute
  LoginRoute: typeof LoginRoute
  YourListRoute: typeof YourListRoute
  EditJobUuidRoute: typeof EditJobUuidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/your-list': {
      id: '/your-list'
      path: '/your-list'
      fullPath: '/your-list'
      preLoaderRoute: typeof YourListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-job': {
      id: '/add-job'
      path: '/add-job'
      fullPath: '/add-job'
      preLoaderRoute: typeof AddJobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-job/$uuid': {
      id: '/edit-job/$uuid'
      path: '/edit-job/$uuid'
      fullPath: '/edit-job/$uuid'
      preLoaderRoute: typeof EditJobUuidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddJobRoute: AddJobRoute,
  LoginRoute: LoginRoute,
  YourListRoute: YourListRoute,
  EditJobUuidRoute: EditJobUuidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
